# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.8'

#Define services
services:

  #PostgreSQL Database for the application
  database:
    #image: "postgres:11"
    image: "postgres:9.6-alpine"
    container_name: emerge-database
    #Volume mounted for database for the storage
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=emerge-database
      - POSTGRES_USER=emerge
      - POSTGRES_PASSWORD=emerge0000

  #Back-end Spring Boot Applications
  backend:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./Analyse_Service
    container_name: Analyse_Service

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=database
      - POSTGRES_DB=emerge-database
      - POSTGRES_USER=emerge
      - POSTGRES_PASSWORD=emerge0000
    ports:
      #- 9003:9003
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine

    links:
      - database

  #Fron-end Angular Application
  frontend:
    container_name: user-interface
    image: user-interface

    build: #./frontend
      target: development
    ports:
      - 3000:3000
    links:
      - backend

#Volumes for DB data
volumes:
  #scrum-data:
  database-data: