#Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.8'

#Define services
services:
  #PostgreSQL Database for the application
  database:

    container_name: emerge_database
    image: postgres:10-alpine
    #image: "postgres:13-alpine"


    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_PASSWORD=emerge0000
      - PGDATA=/var/lib/postgresql/data
      #- POSTGRES_DB:emerge-database
      #- POSTGRES_USER:emerge


    #Volume mounted for database for the storage
    volumes:
      - pgdata:/var/lib/postgresql/data
      - database-data:/docker-entrypoint-initdb.d/emerge_database.sh

    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    restart: unless-stopped


  registry_service:
    container_name: registry_service
    image: teamemerge/registry_service

    build: ./Registry_Service

      #environment:
      #  - DB_SERVER:database
      #- POSTGRES_DB=emerge-database
      #- POSTGRES_USER=emerge
    #- POSTGRES_PASSWORD=emerge0000

    ports:
      - 8761:8761
    links:
      - database




  import_service:
    container_name: import_service
    image: teamemerge/import_service

    build: ./Import_Service

      #environment:
      #  - DB_SERVER=database
      #- POSTGRES_DB=emerge-database
      #- POSTGRES_USER=emerge
    #- POSTGRES_PASSWORD=emerge0000

    ports:
      - 9001:9001
    links:
      - database

  parse_service:
    container_name: parse_service
    image: teamemerge/parse_service

    build: ./Parse_Service

      #environment:
      #  - DB_SERVER=database
      #- POSTGRES_DB:emerge=database
      #- POSTGRES_USER=emerge
    #- POSTGRES_PASSWORD=emerge0000

    ports:
      - 9002:9002
    links:
      - database

  #Back-end Spring Boot Applications
  analyse_service:
    #The docker file in Analyse_Service build the jar and provides the docker image with the following name.
    container_name: analyse_Service
    image: teamemerge/analyse_service

    build: ./Analyse_Service

      #Environment variables for Spring Boot Application.
      #environment:
      #  - DB_SERVER=database
      #- POSTGRES_DB=emerge-database
      #- POSTGRES_USER=emerge
    #- POSTGRES_PASSWORD=emerge0000

    # Forward the exposed port 8080 on the container to port 8080 on the host machine
    ports:
      - 9003:9003

    links:
      - database

    #volumes:
    #  - Analyse_Service/src/main/java/com/Analyse_Service/Analyse_Service/rri/TData.CSV:C:/Users/Rhuli/IdeaProjects/Integrated-Data-Intelligence-Suite/Analyse_Service/src/main/java/com/Analyse_Service/Analyse_Service/rri/TData.CSV

    volumes:
      - type: bind
        source: C:/Users/Rhuli/IdeaProjects/Integrated-Data-Intelligence-Suite/Analyse_Service/src/main/java/com/Analyse_Service/Analyse_Service/rri/TData.CSV
        target: Analyse_Service/src/main/java/com/Analyse_Service/Analyse_Service/rri/TData.CSV




  visualize_service:
    container_name: visualize_service
    image: teamemerge/visualize_service

    build: ./Visualize_Service

      #environment:
      #  - DB_SERVER=database
      #- POSTGRES_DB=emerge-database
      #- POSTGRES_USER=emerge
    #- POSTGRES_PASSWORD=emerge0000

    ports:
      - 9004:9004
    links:
      - database

  user_service:
    container_name: user_service
    image: teamemerge/user_service

    build: ./User_Service

    #environment:
    #  - DB_SERVER=database
    #  - POSTGRES_DB=UserServiceDatabase
    #  - POSTGRES_USER=emerge
    #  - POSTGRES_PASSWORD=emerge0000

    ports:
      - 9005:9005
    links:
      - database


  report_service:
    container_name: report_service
    image: teamemerge/report_service

    build: ./Report_Service

    #environment:
    #  - DB_SERVER=database
    #  - POSTGRES_DB=UserServiceDatabase
    #  - POSTGRES_USER=emerge
    #  - POSTGRES_PASSWORD=emerge0000

    ports:
      - 9006:9006
    links:
      - database


  gateway_service:
    container_name: gateway_service
    image: teamemerge/gateway_service

    build: ./Gateway_Service

      #environment:
      #  - DB_SERVER=database
      #- POSTGRES_DB=emerge-database
      #- POSTGRES_USER=emerge
    #- POSTGRES_PASSWORD=emerge0000

    ports:
      - 9000:9000
    links:
      - database



  #user_interface
  user-interface:
    container_name: User-Interface
    image: teamemerge/user_interface

    build:
      context: ../frontend
      args:
        REACT_APP_BACKEND_HOST: ${REACT_APP_BACKEND_HOST}
        REACT_APP_BACKEND_PORT: ${REACT_APP_BACKEND_PORT}
      #target: development

    ports:
      - 3000:3000
    links:
      - gateway_service

    environment:
      - REACT_APP_BACKEND_HOST=localhost
        REACT_APP_BACKEND_PORT=9000

#Volumes for DB data
volumes:
  database-data:
  pgdata:
  #Analyse_Service/src/main/java/com/Analyse_Service/Analyse_Service/rri/TData.CSV:

