server:
  port: 9004

spring:
  application:
    name: Visualize-Service

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
