apiVersion: v1
kind: ConfigMap
metadata:
  name: user-interface-configmap
data:
  backend_host: gateway-service-svc.default.svc.cluster.local
  backend_port: "9000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface
  labels:
    app: user-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
        - name: user-interface
          image: teamemerge/user_interface:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-interface-configmap
                  key: backend_host
            - name: REACT_APP_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-interface-configmap
                  key: backend_port

---
apiVersion: v1
kind: Service
metadata:
  name: user-interface-svc
spec:
  type: LoadBalancer
  selector:
    app: user-interface
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #nodePort: 30000







